BaSP-TG-10: ADD Get, GetById, Create for Task
BaSP-a2022/lucas-b-trackgenix-server pull request #22
Opened 2022-10-14 19:18 UTC by fede230298

- New model for Tasks
- Router implementation for Tasks
- Add GET to route '/tasks' to get a complete list of Tasks
- Add GET to route '/tasks/:id' to get a Task filtered by its ID
- Add POST to route '/tasks' to create a new Task
- Added validations with Joi as a middleware
- Updated Postman collection

2022-10-14 20:39 UTC, GinaSchP requested changes

2022-10-14 20:39 UTC, GinaSchP commented on src/controllers/tasks.js
> +    return res.json({
The status of the error is missing, must be:
 return res.status(400).json({
               message: error, // o error.toString()
               data: undefined,
               error: true
           });

2022-10-14 20:39 UTC, GinaSchP commented on src/controllers/tasks.js
> +    return res.json({
same as above

2022-10-14 20:39 UTC, GinaSchP commented on src/controllers/tasks.js
> +    const tasks = await Tasks.find();
Here you can implement Tasks.find(req.query), and if there is a filter, it is applied directly.

2022-10-14 21:04 UTC, GinaSchP requested changes

2022-10-14 21:04 UTC, GinaSchP commented on src/controllers/tasks.js
> +    const tasks = await Tasks.findById(id);
"tasks" should be "task" Also, you must validate if the method returns something (with an if statement) and if not return a 404 error with a not found message.

2022-10-15 01:50 UTC, lmalvasia commented on src/routes/index.js
> +const tasksRouter = require('./tasks');
All the imports should be at the beginning of the project. We also have to use the "import" (ES6).

2022-10-15 01:50 UTC, lmalvasia commented on src/routes/tasks.js
> +const express = require('express');
use "import" to import the files and libraries

2022-10-15 01:50 UTC, lmalvasia commented on src/routes/tasks.js
> +module.exports = router;
export router

2022-10-15 01:50 UTC, lmalvasia commented on src/validations/tasks.js
> +export const validateCreation = (req, res, next) => {
```suggestion
const validateTaskBody = (req, res, next) => {
```

2022-10-15 01:50 UTC, lmalvasia commented on src/validations/tasks.js
> +export default {
export default validateTaskBody;

2022-10-15 01:51 UTC, lmalvasia commented on src/controllers/tasks.js
> +    return res.status(200).json({
Add a validation to return a different message when "task" is undefined (not exist).

2022-10-15 22:55 UTC, lmalvasia commented on src/controllers/tasks.js
> +    if (tasks.length === 0) {
```suggestion
    if (!tasks.length) {
```

2022-10-15 22:55 UTC, lmalvasia commented on src/controllers/tasks.js
> +    if (task === null) {
```suggestion
    if (!task) {
```

2022-10-15 23:20 UTC, lmalvasia commented on src/validations/tasks.js
> +export const validateQuery = (req, res, next) => {
```suggestion
export const validateTaskQueryParams = (req, res, next) => {
```

2022-10-15 23:32 UTC, lmalvasia approved these changes

2022-10-16 17:34 UTC, GinaSchP submitted a review, later dismissed

2022-10-16 18:54 UTC, GinaSchP approved these changes

2022-10-16 19:02 UTC, merged