TG-9: Creation of edit function on Super Admins
BaSP-a2022/lucas-b-trackgenix-server pull request #23
Opened 2022-10-14 20:03 UTC by SteampunkMatu

Added Edit function on Super Admins section

2022-10-14 20:52 UTC, GinaSchP requested changes

2022-10-14 20:52 UTC, GinaSchP commented on src/controllers/super-admins.js
> +      { _id: id },
this line must be SuperAdmins.findByInAndUpdate(id, req.body, { new: true },)

2022-10-14 20:52 UTC, GinaSchP commented on src/controllers/super-admins.js
> +    return res.json({
The ststus of error is missing, must be: 
return res.status(400).json({
               message: error, // o error.toString()
               data: undefined,
               error: true
           });

2022-10-14 20:52 UTC, GinaSchP commented on src/controllers/super-admins.js
> +    return res.json({
same as above

2022-10-15 01:57 UTC, lmalvasia commented on src/index.js
> +import superAdminsRoutes from './routes/super-admins';
You have to import this inside the ./routes/index.js file (check the Fede's PR)

2022-10-15 01:57 UTC, lmalvasia commented on src/models/Super-admins.js
> +
remove this space

2022-10-15 01:57 UTC, lmalvasia commented on src/models/Super-admins.js
> +
remove this another space

2022-10-15 01:57 UTC, lmalvasia commented on src/validations/super-admins.js
> +const validateCreation = (req, res, next) => {
```suggestion
const validateSuperAdminBody = (req, res, next) => {
```

2022-10-15 01:57 UTC, lmalvasia commented on src/validations/super-admins.js
> +const validateCreation = (req, res, next) => {
or 
```suggestion
const validateSuperAdminCreationBody = (req, res, next) => {
```

2022-10-15 01:57 UTC, lmalvasia commented on src/validations/super-admins.js
> +export default {
export default superAdminValidation;

2022-10-15 01:57 UTC, lmalvasia commented on src/controllers/super-admins.js
> +    const result = await SuperAdmins.findByIdAndDelete(id);
What happen when we send an invalid id? (Super admin does not exist)

2022-10-15 15:20 UTC, lmalvasia commented on src/controllers/super-admins.js
> +export default {
Remove this export default and export the functions individually

2022-10-15 22:59 UTC, lmalvasia approved these changes

2022-10-16 17:34 UTC, GinaSchP approved these changes

2022-10-16 17:34 UTC, merged