BaSP-TG-13: Edit and Delete function created
BaSP-a2022/lucas-b-trackgenix-server pull request #24
Opened 2022-10-15 00:32 UTC by disimoneleandro

2022-10-15 17:54 UTC, GinaSchP requested changes

2022-10-15 17:54 UTC, GinaSchP commented on src/controllers/time-sheets.js
> +    const result = await TimeSheets.findByIdAndUpdate(
this line must be TimeSheets.findByInAndUpdate(id, req.body, { new: true },)

2022-10-15 17:54 UTC, GinaSchP commented on src/controllers/time-sheets.js
> +    return res.status(200).json({
before throwing a status 200 you must validate that there is a timesheet in result, otherwise throw a 404

2022-10-15 17:54 UTC, GinaSchP commented on src/controllers/time-sheets.js
> +    return res.json({
The ststus of error is missing, must be:
return res.status(400).json({
message: error, // o error.toString()
data: undefined,
error: true
});

2022-10-15 17:54 UTC, GinaSchP commented on src/controllers/time-sheets.js
> +    return res.status(200).json({
same as above, you must validate that there is a timesheet in result, otherwise throw a 404

2022-10-15 17:54 UTC, GinaSchP commented on src/controllers/time-sheets.js
> +    return res.json({
Same as above

2022-10-15 23:07 UTC, lmalvasia commented on src/controllers/time-sheets.js
> +    const timeSheets = await TimeSheets.find();
You can use the query params to filter the data.
(Check Fede's PR)

2022-10-15 23:07 UTC, lmalvasia commented on src/controllers/time-sheets.js
> +    return res.status(200).json({
@disimoneleandro check if this is necessary because I think that the findByIdAndUpdate function always return a value (the updated entity). Check what happens when we send a invalid id.

2022-10-15 23:07 UTC, lmalvasia commented on src/controllers/time-sheets.js
> +    return res.status(200).json({
same as the other comment

2022-10-15 23:25 UTC, disimoneleandro commented on src/controllers/time-sheets.js
> +    return res.status(200).json({
change it to:  
const result = await TimeSheets.findByIdAndUpdate(
      id,
      req.body,
      { new: true },
    );

2022-10-15 23:27 UTC, disimoneleandro commented on src/controllers/time-sheets.js
> +    return res.json({
It was modified

2022-10-16 00:11 UTC, lmalvasia submitted a review, later dismissed

2022-10-16 00:11 UTC, lmalvasia commented on src/controllers/time-sheets.js
> +    return res.status(200).json({
As I mentioned above, this valdiation is not necessary because when the time sheet does not exist, the findByIdAndDelete method returns an error and the server should catch the error.

2022-10-16 17:34 UTC, GinaSchP approved these changes

2022-10-16 23:54 UTC, lmalvasia commented on src/validations/time-sheets.js
> +const validateCreation = (req, res, next) => {
```suggestion
const validateTimeSheetBody = (req, res, next) => {
```

2022-10-16 23:54 UTC, lmalvasia commented on src/validations/time-sheets.js
> +export default validateCreation;
```suggestion
export default validateTimeSheetBody;
```

2022-10-16 23:59 UTC, lmalvasia approved these changes

2022-10-16 23:59 UTC, merged